# Generated by Django 4.0.4 on 2022-04-29 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notebook',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('marca', models.CharField(max_length=200)),
                ('modelo', models.CharField(max_length=200)),
                ('especificacoes_tecnicas', models.TextField()),
                ('preco', models.FloatField()),
            ],
        ),
    ]
