# Generated by Django 4.0.4 on 2022-04-29 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_solicitacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacao',
            name='grupo_prioritario',
            field=models.CharField(choices=[(1, 'Oriundos de escola pública'), (2, 'Pretos oriundos de escola privada'), (3, 'Brancos oriundos de escola privada'), (0, 'Não possui')], default='', max_length=1),
            preserve_default=False,
        ),
    ]
