# Generated by Django 4.0.4 on 2022-04-29 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_recursos'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacao',
            name='notebook',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main.notebook'),
            preserve_default=False,
        ),
    ]
