# Generated by Django 4.0.4 on 2022-05-04 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_recursos_valor_disponivel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recursos',
            name='porcentagem_gp1',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='recursos',
            name='porcentagem_gp2',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='recursos',
            name='porcentagem_gp3',
            field=models.FloatField(),
        ),
    ]
